#!/bin/bash

echo '===================================='
echo 'BEGIN /usr/local/bin/docker-dev-user'
echo '===================================='

echo '-----------------------'
echo 'BEGIN installing Heroku'
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh # Install Heroku Toolbelt
wait
heroku version
wait
heroku version
wait
heroku version
wait
echo 'FINISHED installing Heroku'
echo '--------------------------'

echo '======================================='
echo 'FINISHED /usr/local/bin/docker-dev-user'
echo '======================================='
