#!/bin/bash

echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
echo 'BEGIN /usr/local/bin/docker-hyde'
echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'

/usr/local/bin/docker-root-aptget

echo '****************************************************'
echo 'BEGIN transforming Minimal Edition into Hyde Edition'
echo '****************************************************'
/usr/local/bin/docker-hyde-root
echo '*******************************************************'
echo 'FINISHED transforming Minimal Edition into Hyde Edition'
echo '*******************************************************'

/usr/local/bin/docker-root-finalize

echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
echo 'FINISHED /usr/local/bin/docker-hyde'
echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
