#!/bin/bash

/usr/local/bin/docker-dev-root

echo '====================================='
echo 'BEGIN /usr/local/bin/docker-hyde-root'
echo '====================================='

echo '---------------------------------------'
echo 'apt-get install -y python2.7 python-pip'
apt-get install -y python2.7 python-pip

echo '----------------'
echo 'pip install hyde'
pip install hyde

echo '========================================'
echo 'FINISHED /usr/local/bin/docker-hyde-root'
echo '========================================'

su -c /usr/local/bin/docker-hyde-user winner
su -c /usr/local/bin/docker-hyde-check winner
