#!/bin/bash

print_timestamp ()
{
  echo '------------------------------------'
  echo 'BEGIN cat /home/winner/timestamp.txt'
  echo '------------------------------------'
  cat /home/winner/timestamp.txt
  echo '---------------------------------------'
  echo 'FINISHED cat /home/winner/timestamp.txt'
  echo '---------------------------------------'
}

echo '========================================='
echo 'BEGIN /usr/local/bin/docker-user-finalize'
echo '========================================='

print_timestamp

echo 'Filling in /home/winner/timestamp.txt'
DATE=`date +%Y_%m%d_%H%M -u`
echo "Build Date: $DATE" >> /home/winner/timestamp.txt
echo '' >> /home/winner/timestamp.txt

print_timestamp

echo '============================================'
echo 'FINISHED /usr/local/bin/docker-user-finalize'
echo '============================================'
