#!/bin/bash

echo '=============================================='
echo 'BEGIN /usr/local/bin/docker-rbenv-jekyll-user'
echo '=============================================='

# Set of gems to install for each version of Ruby
function install_gems {
  echo '-------------------'
  echo 'gem install bundler'
  gem install bundler

  # The latest versions of Rails, PostgreSQL, Nokogiri, and MailCatcher
  echo '------------------'
  echo 'gem install jekyll'
  gem install jekyll
}

# Input parameter: 'ruby-x.y'
function install_ruby_version {
  ruby_version=$1
  echo '++++++++++++++++++++++++++++++++'
  echo "time rbenv install $ruby_version"
  time rbenv install $ruby_version
  echo ' /\'
  echo '/  \'
  echo "Time to install Ruby $rubyversion"
  rbenv global $ruby_version
  time install_gems
  echo ' /\'
  echo '/  \'
  echo 'Time to install gems'
}

# Allow rbenv commands to work
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv

# Latest versions of Ruby
# https://www.ruby-lang.org/en/downloads/
time install_ruby_version 2.3.1
echo ' /\'
echo '/  \'
echo 'Time to install Ruby 2.3.1 and gems'

rbenv global 2.3.1

echo '*********************************'
echo 'FINISHED installing Ruby on Rails'
echo '*********************************'

echo '================================================='
echo 'FINISHED /usr/local/bin/docker-rbenv-jekyll-user'
echo '================================================='
