#!/bin/bash

echo '====================================='
echo 'BEGIN /usr/local/bin/docker-min-check'
echo '====================================='

# Check Perl status
echo '-------'
echo 'perl -v'
perl -v

echo '--------------'
echo 'sudo --version'
sudo --version

echo '------'
echo 'whoami'
whoami

echo '-----------'
echo 'sudo whoami'
sudo whoami

echo '--------------'
echo 'nano --version'
nano --version

echo '--------------'
echo 'tree --version'
tree --version

echo '-------'
echo 'tmux -V'
tmux -V

echo '========================================'
echo 'FINISHED /usr/local/bin/docker-min-check'
echo '========================================'
