#!/bin/bash

echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
echo 'BEGIN /usr/local/bin/docker-min'
echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'

time /usr/local/bin/docker-root-aptget
echo ' /\'
echo '/  \'
echo 'Time to execute /usr/local/bin/docker-root-aptget'

echo '***********************************************************'
echo 'BEGIN transforming minimal debootstrap into Minimal Edition'
echo '***********************************************************'

time /usr/local/bin/docker-min-root
echo ' /\'
echo '/  \'
echo 'Time to execute /usr/local/bin/docker-min-root'

echo '**************************************************************'
echo 'FINISHED transforming minimal debootstrap into Minimal Edition'
echo '**************************************************************'

time /usr/local/bin/docker-root-finalize
echo ' /\'
echo '/  \'
echo 'Time to execute /usr/local/bin/docker-root-finalize'

echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
echo 'FINISHED /usr/local/bin/docker-min'
echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
