#!/bin/bash

/usr/local/bin/docker-dev-root

echo '=============================================='
echo 'BEGIN /usr/local/bin/docker-rbenv-rubymn2-root'
echo '=============================================='

echo '================================================='
echo 'FINISHED /usr/local/bin/docker-rbenv-rubymn2-root'
echo '================================================='

su -c /usr/local/bin/docker-rbenv-rubymn2-user winner
su -c /usr/local/bin/docker-rbenv-rubymn2-check winner
