#!/bin/bash

echo '=========================================='
echo 'BEGIN /usr/local/bin/docker-rbenv-min-user'
echo '=========================================='

echo '**********************'
echo 'BEGIN installing rbenv'

echo '---------------------------'
echo 'BEGIN installation of rbenv'
echo 'git clone https://github.com/sstephenson/rbenv.git /home/winner/.rbenv'
git clone https://github.com/sstephenson/rbenv.git /home/winner/.rbenv
wait
echo 'Updating /home/winner/.bashrc'
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> /home/winner/.bashrc
echo 'eval "$(rbenv init -)"' >> /home/winner/.bashrc
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv
echo 'FINISHED installation of rbenv'
echo '------------------------------'
echo ''
echo '--------------------------------'
echo 'BEGIN installation of ruby-build'
git clone https://github.com/sstephenson/ruby-build.git /home/winner/.rbenv/plugins/ruby-build
wait
echo 'FINISHED installation of ruby-build'
echo '-----------------------------------'

echo '-----------------------------------------'
echo 'BEGIN installation of rbenv-communal-gems'
mkdir -p /home/winner/.rbenv/plugins
git clone git://github.com/tpope/rbenv-communal-gems.git \
  /home/winner/.rbenv/plugins/rbenv-communal-gems
wait
echo '---------------------'
echo 'rbenv communize --all'
rbenv communize --all
echo 'FINISHED installation of rbenv-communal-gems'
echo '--------------------------------------------'

echo '--------------------------------------'
echo 'BEGIN installation of rbenv-gem-rehash'
git clone https://github.com/sstephenson/rbenv-gem-rehash.git /home/winner/.rbenv/plugins/rbenv-gem-rehash
echo 'FINISHED installation of rbenv-gem-rehash'
echo '-----------------------------------------'

echo '------------'
echo 'rbenv rehash'
rbenv rehash

echo '----------------------------------'
echo 'BEGIN installation of rbenv-update'
mkdir -p "$(rbenv root)/plugins"
git clone https://github.com/rkh/rbenv-update.git "$(rbenv root)/plugins/rbenv-update"
echo 'FINISHED installation of rbenv-update'
echo '-------------------------------------'

echo 'gem: --no-document' > /home/winner/.gemrc
rbenv install -l

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv

echo 'FINISHED installing rbenv'
echo '*************************'

echo '============================================='
echo 'FINISHED /usr/local/bin/docker-rbenv-min-user'
echo '============================================='
