#!/bin/bash

echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
echo 'BEGIN /usr/local/bin/docker-rbenv-jekyll'
echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'

time /usr/local/bin/docker-root-aptget
echo ' /\'
echo '/  \'
echo 'Time to execute /usr/local/bin/docker-root-aptget'

echo '*************************************************************'
echo 'BEGIN transforming Minimal Edition into rbenv-jekyll Edition'
echo '*************************************************************'

time /usr/local/bin/docker-rbenv-jekyll-root
echo ' /\'
echo '/  \'
echo 'Time to execute /usr/local/bin/docker-rbenv-jekyll-root'

echo '****************************************************************'
echo 'FINISHED transforming Minimal Edition into rbenv-jekyll Edition'
echo '****************************************************************'

time /usr/local/bin/docker-root-finalize
echo ' /\'
echo '/  \'
echo 'Time to execute /usr/local/bin/docker-root-finalize'

echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
echo 'FINISHED /usr/local/bin/docker-rbenv-jekyll'
echo '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
