#!/bin/bash

/usr/local/bin/docker-dev-root

echo '=============================================='
echo 'BEGIN /usr/local/bin/docker-rbenv-avatar-root'
echo '=============================================='

echo '================================================='
echo 'FINISHED /usr/local/bin/docker-rbenv-avatar-root'
echo '================================================='

su -c /usr/local/bin/docker-rbenv-avatar-user winner
su -c /usr/local/bin/docker-rbenv-avatar-check winner
