#!/bin/bash

SECONDS=0

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/aptget.sh | sudo bash

echo '*******************************'
echo 'BEGIN transforming min into dev'
echo '*******************************'

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

echo '-----------------------------------------------------------------------------------------------------------'
echo 'Downloading scripts to be executed as winner from https://github.com/jhsu802701/docker-debian-jessie-custom'
curl 'https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/user1.sh' > '/usr/local/bin/docker-dev-user1'
curl 'https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/user2.sh' > '/usr/local/bin/docker-dev-user2'
curl 'https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/check.sh' > '/usr/local/bin/docker-dev-check' 
curl 'https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-user.sh' > '/usr/local/bin/docker-user-finalize'

echo '------------------------------------'
echo 'Making downloaded scripts executable'
chmod +x /usr/local/bin/*

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/dev/root.sh | sudo bash
su -c /usr/local/bin/docker-dev-user1 winner
su -c /usr/local/bin/docker-dev-user2 winner

echo '-------------------'
echo 'BEGIN sanity checks'
echo '-------------------'
su -c /usr/local/bin/docker-dev-check winner
echo '----------------------'
echo 'FINISHED sanity checks'
echo '----------------------'

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"

echo '**********************************'
echo 'FINISHED transforming min into dev'
echo '**********************************'

curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-root.sh | sudo bash
curl https://raw.githubusercontent.com/jhsu802701/docker-debian-jessie-custom/master/finalize-user.sh | bash

echo '-------------'
echo 'Time elapsed:'
echo "$(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds"
