#!/bin/bash

/usr/local/bin/docker-rbenv-min-check

echo '==============================================='
echo 'BEGIN /usr/local/bin/docker-rbenv-losemoneyfast-check'
echo '==============================================='

# Allow rbenv commands to work
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
type rbenv

echo '-------'
echo 'ruby -v'
ruby -v

echo '--------'
echo 'rails -v'
rails -v

echo '--------------'
echo 'rbenv versions'
rbenv versions

echo '------------------'
echo 'gem list "^rails$"'
gem list "^rails$"

echo '---------------------'
echo 'gem list "^nokogiri$"'
gem list "^nokogiri$"

echo '---------------'
echo 'gem list "^pg$"'
gem list "^pg$"

echo '------------------------'
echo 'gem list "^mailcatcher$"'
gem list "^mailcatcher$"

echo '=================================================='
echo 'FINISHED /usr/local/bin/docker-rbenv-losemoneyfast-check'
echo '=================================================='
